package io.adev.test_task.data.cloud.exception;

public class NetworkException extends Exception {
}
